version: '3.1'

services:

  node:
    image: node
    stdin_open: true
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/share

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
