version: '3.1'

services:

  node:
    image: node:10.1.0
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/share
    environment:
      PORT: 80
      MONGODB: mongo:27017
    command: >
      bash -c "cd /share && npm install && npm start"

  mongo:
    image: mongo:3.6.4
    restart: always
    volumes:
      - ./data:/data/db
